### PR TITLE
Main page and sign up form impl

### PR DESCRIPTION
**Pull request by sophiacodes**

### CODE REVIEW

**Review by jdville03 — CHANGES_REQUESTED** [review]
@sophiacodes this generally looks good to me but I think there is an issue breaking the build that needs to get fixed. This is what is in the Netlify logs for the preview deploy failure:
```
7:57:54 PM: error Generating JavaScript bundles failed
7:57:54 PM: 
7:57:54 PM:   Error: ./src/components/sections/LegalProtocol.jsx
7:57:54 PM:   Module not found: Error: Can't resolve '../../scss/modules/legalprotocol.modul  e.scss' in '/opt/build/repo/src/components/sections'
7:57:54 PM:   resolve '../../scss/modules/legalprotocol.module.scss' in '/opt/build/repo/src  /components/sections'
7:57:54 PM:     using description file: /opt/build/repo/package.json (relative path: ./src/c  omponents/sections)
7:57:54 PM:       Field 'browser' doesn't contain a valid alias configuration
7:57:54 PM:       using description file: /opt/build/repo/package.json (relative path: ./src  /scss/modules/legalprotocol.module.scss)
7:57:54 PM:         no extension
7:57:54 PM:           Field 'browser' doesn't contain a valid alias configuration
7:57:54 PM:           /opt/build/repo/src/scss/modules/legalprotocol.module.scss doesn't exi  st
7:57:54 PM:         .mjs
7:57:54 PM:           Field 'browser' doesn't contain a valid alias configuration
7:57:54 PM:           /opt/build/repo/src/scss/modules/legalprotocol.module.scss.mjs doesn't   exist
7:57:54 PM:         .js
7:57:54 PM:           Field 'browser' doesn't contain a valid alias configuration
7:57:54 PM:           /opt/build/repo/src/scss/modules/legalprotocol.module.scss.js doesn't   exist
7:57:54 PM:         .jsx
7:57:54 PM:           Field 'browser' doesn't contain a valid alias configuration
7:57:54 PM:           /opt/build/repo/src/scss/modules/legalprotocol.module.scss.jsx doesn't   exist
7:57:54 PM:         .wasm
7:57:54 PM:           Field 'browser' doesn't contain a valid alias configuration
7:57:55 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
7:57:54 PM:           /opt/build/repo/src/scss/modules/legalprotocol.module.scss.wasm doesn'  t exist
7:57:54 PM:         .json
```
I may have more comments after being able to see the preview.

**Comment by sophiacodes** [comment]
@jdville03 issue resolved! Thanks for the heads up

**Comment by jdville03** [comment]
Thanks for the fixes and getting the preview up! I'll pass along a few comments today. Nothing major but see a few broken links and want to take a closer run through it all.

**Comment by jdville03** [comment]
@sophiacodes in the interest of time and to be able to validate my changes live, I made some updates in the form of a new PR #101 to merge into this one. Hope you don't mind and let me know if you have any questions on it.

**Review by jdville03 — APPROVED** [review]
This looks good to merge now

**Comment by mroth** [comment]
Merge overridden on request, GH seems to have been improperly blocked waiting for deploy status.

**Pull request merged**
