### PR TITLE
Committing updated package and yarn locks after running clean against current node lts / npm versions

### PR DESCRIPTION
**Pull request by rjfranco**
It seems there's still something inconsistent about what I'm doing and what's typical in people's environments. Things run as expected but wether I run `npm i` or `yarn` I end up generating updates. I committed those and added them here.

My current node is 8.11.4 (a step behind current its, but 8.12.0 hasn't been added to nodenv yet), npm is 6.4.1, and yarn is 1.10.1 — anything there stand out as being different from what's expected?

We should also likely standardize against just one package manager, there's some inconsistencies between how they resolve dependencies — I tend to like yarn's behavior more but I'm good either way really.

### CODE REVIEW

**Comment by mroth** [comment]
Agree we should standardize on one (and remove the lock file for the other to avoid confusion).

FWIW my personal vote would be for npm for the following (devops/community)-ish reasons (though admittedly, I have far from perfect knowledge here):

- standard built-in default tool, e.g. one less dependency for open source contributors to install (or for us to install/manage in container build process), and means someone will "do the right thing" by default if they don't read the README.
- AFAIK the initial deficiencies yarn was intended to address have long since been addressed in npm, especially now that lock files are generated by default?
- `npm ci` (which relies on `package-lock.json`) is really good for dramatically speeding dependency installs when you don't need to check for updates (such as during CI, or when building a container etc).

However I suspect you two both know more about the overall ecosystem than me here, so will leave the decision to you!

**Comment by jtrein** [comment]
@mroth Thanks for reminding me to look at `npm ci` - pretty epic!

I personally like `yarn` better, but your points make sense about why to stick with `npm`. I do think NPM has improved quite a bit, which is I think due to Yarn doing their own thing in response to NPM issues.

To me, it really doesn't matter too much if there's 2 different ones, as I've never experienced an app having a runtime error, because someone used one over the other. The issues happen when you mix - I have had errors when doing that, which is the issue @rjfranco alluded to a bit.

However, to keep things super-simple I vote for NPM. If people want to use Yarn locally, it's chill, just don't commit the Yarn.lock file.

**Comment by rjfranco** [comment]
I’m good with an npm vote too. I’ll cut out the yarn lock and commit that.

**Comment by rjfranco** [comment]
Is it safe then to merge in the package-lock changes as well?

**Review by jtrein — APPROVED** [review]
I think it looks good.

**Pull request merged**
