### PR TITLE
Style 404 on Static Page

### PR DESCRIPTION
**Pull request by RunRafter**

### CODE REVIEW

**Review by jtrein — APPROVED** [review]
Looks good, and thank you for your attention on this! Much more aligned with our app, now.

I have fixed the fonts, as they weren't loaded. I also removed an unused page.

**Comment by jtrein** [comment]
@RunRafter There's a page reload for some reason controlled by Gatsby:

https://deploy-preview-78--openlaw-website.netlify.com/wow
Becomes
https://deploy-preview-78--openlaw-website.netlify.com/wow?no-cache=1

See how it appends the `?no-cache=1`? Could you maybe look into that and see if it's not huge to fix?

I'll merge this for now to get something in front of users.

**Comment by RunRafter** [comment]
@jtrein Good catch!  Did some investigation so it seems like they fixed this in newer versions of gatsby  https://github.com/gatsbyjs/gatsby/issues/8297

**Comment by RunRafter** [comment]
Wanted to check in with you whether we want to go through with upgrading gatsby! :)

**Pull request merged**
