### PR TITLE
Adds Media Kit logos

### LINKED ISSUE #63: Create an OpenLaw Press/Media Kit
I've noticed a few articles written about us and the writer couldn't access our logo easily since it was an SVG (which isn't a bad thing), so they took a screenshot. They need the option of using multiple file formats (we don't know what their CMS accepts) and also having facts about us they don't have to email, or call us for.

- [ ] PDF (fact sheet, background, founders, etc.)
- [ ] `opelaw-mediakit.zip` file of Logos, nice images
---

References: 
- https://en.wikipedia.org/wiki/Press_kit
- **Example of a written Press Kit:** https://kaleido.io/wp-content/uploads/2018/06/Kaleido_Press_Kit.pdf

cc: @atgrif

### PR DESCRIPTION
**Pull request by jtrein**
Fixes #63 

A lot of media outlets don't have access to our logos so they've been taking screenshots of our marketing page "hero section" logo.

**Netlify static zip file**
- Adds `static/openlaw-media-logos.zip`
- Adds 1x, 2x, 3x PNG of circle only
- Adds 1x, 2x PNG of vertical, and horizontal
- Adds SVG of circle only, horizontal, and vertical

**Footer Menu**
- Adds new link, "Media Kit" under "Info" section
- Fixes a small whitespace UI bug with some footer links

### CODE REVIEW

**Comment by jtrein** [comment]
Will need to update the app's footer as well. I will handle that in another issue inside the openlaw-app repo.

**Comment by jtrein** [comment]
To check the .zip link in the deploy preview: https://deploy-preview-97--openlaw-website.netlify.com/openlaw-media-logos.zip?ref=footer

**Comment by jtrein** [comment]
@jdville03 @mroth Any advice on the build? What's the new way to deploy this lil guy? It's stuck on yellow `deploy/netlify`.

**Comment by mroth** [comment]
> @jdville03 @mroth Any advice on the build? What's the new way to deploy this lil guy? It's stuck on yellow `deploy/netlify`.

I think this was a GitHub error. Looking at Netlify logs it seems to have deployed fine.
```
7:46:47 AM: Build ready to start
7:46:53 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
7:46:53 AM: build-image tag: v3.3.2
7:46:53 AM: buildbot version: 75cd99f62ada9e21edea53208e8baf0eab85a045
7:46:53 AM: Fetching cached dependencies
7:46:53 AM: Failed to fetch cache, continuing with build
7:46:53 AM: Starting to prepare the repo for build
7:46:54 AM: No cached dependencies found. Cloning fresh repo
7:46:54 AM: git clone https://github.com/openlawteam/openlaw-website
7:46:54 AM: Preparing Git Reference pull/97/head
7:46:55 AM: Found netlify.toml. Overriding site configuration
7:46:55 AM: Starting build script
7:46:55 AM: Installing dependencies
7:46:57 AM: Downloading and installing node v10.16.0...
7:46:57 AM: Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz...
7:46:58 AM: 
####
7:46:58 AM:                            6.1%
7:46:58 AM: 
##############
7:46:58 AM: ##################################################          88.9%
7:46:58 AM: 
###########################################################
7:46:58 AM: ############# 100.0%
7:46:58 AM: Computing checksum with sha256sum
7:46:58 AM: Checksums matched!
7:47:01 AM: Now using node v10.16.0 (npm v6.9.0)
7:47:01 AM: Attempting ruby version 2.6.2, read from environment
7:47:03 AM: Using ruby version 2.6.2
7:47:04 AM: Using PHP version 5.6
7:47:04 AM: Started restoring cached node modules
7:47:04 AM: Finished restoring cached node modules
7:47:04 AM: Installing NPM modules using NPM version 6.9.0
7:47:50 AM: > sharp@0.20.8 install /opt/build/repo/node_modules/sharp
7:47:50 AM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
7:47:50 AM: info
7:47:50 AM: sharp Detected globally-installed libvips v8.6.2
7:47:50 AM: info sharp Building from source via node-gyp
7:47:53 AM: make: Entering directory '/opt/build/repo/node_modules/sharp/build'
7:47:53 AM:   TOUCH Release/obj.target/libvips-cpp.stamp
7:47:54 AM:   CXX(target) Release/obj.target/sharp/src/common.o
7:48:01 AM:   CXX(target) Release/obj.target/sharp/src/metadata.o
7:48:04 AM:   CXX(target) Release/obj.target/sharp/src/stats.o
7:48:06 AM:   CXX(target) Release/obj.target/sharp/src/operations.o
7:48:09 AM:   CXX(target) Release/obj.target/sharp/src/pipeline.o
7:48:14 AM:   CXX(target) Release/obj.target/sharp/src/sharp.o
7:48:16 AM:   CXX(target) Release/obj.target/sharp/src/utilities.o
7:48:18 AM:   SOLINK_MODULE(target) Release/obj.target/sharp.node
7:48:19 AM:   COPY Release/sharp.node
7:48:19 AM: make: Leaving directory '/opt/build/repo/node_modules/sharp/build'
7:48:19 AM: > node-sass@4.9.2 install /opt/build/repo/node_modules/node-sass
7:48:19 AM: > node scripts/install.js
7:48:20 AM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.2/linux-x64-64_binding.node
7:48:20 AM: Download complete
7:48:20 AM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-64/binding.node
7:48:21 AM: Caching binary to /opt/buildhome/.npm/node-sass/4.9.2/linux-x64-64_binding.node
7:48:21 AM: > pngquant-bin@5.0.0 postinstall /opt/build/repo/node_modules/pngquant-bin
7:48:21 AM: > node lib/install.js
7:48:22 AM:   ✔ pngquant pre-build test passed successfully
7:48:22 AM: > cwebp-bin@4.0.0 postinstall /opt/build/repo/node_modules/cwebp-bin
7:48:22 AM: > node lib/install.js
7:48:23 AM:   ✔ cwebp pre-build test passed successfully
7:48:23 AM: > node-sass@4.9.2 postinstall /opt/build/repo/node_modules/node-sass
7:48:23 AM: > node scripts/build.js
7:48:23 AM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-64/binding.node
7:48:23 AM: Testing binary
7:48:23 AM: Binary is fine
7:48:27 AM: npm
7:48:27 AM:  WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
7:48:27 AM: npm WARN notsup
7:48:27 AM:  SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:48:27 AM: added 2102 packages from 1199 contributors and audited 22866 packages in 82.282s
7:48:27 AM: found 394 vulnerabilities (10 low, 365 moderate, 19 high)
7:48:27 AM:   run `npm audit fix` to fix them, or `npm audit` for details
7:48:27 AM: NPM modules installed
7:48:28 AM: Started restoring cached go cache
7:48:28 AM: Finished restoring cached go cache
7:48:28 AM: unset GOOS;
7:48:28 AM: unset GOARCH;
7:48:28 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
7:48:28 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
7:48:28 AM: go version >&2;
7:48:28 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
7:48:28 AM: go version go1.12 linux/amd64
7:48:28 AM: Installing missing commands
7:48:28 AM: Verify run directory
7:48:28 AM: Executing user command: gatsby build
7:48:31 AM: success open and validate gatsby-configs — 0.013 s
7:48:31 AM: warning Plugin gatsby-source-filesystem is not compatible with your gatsby version 2.0.67 - It requires gatsby@^1.9.250
7:48:31 AM: warning Plugin gatsby-plugin-catch-links is not compatible with your gatsby version 2.0.67 - It requires gatsby@^1.0.0
7:48:31 AM: success load plugins — 0.300 s
7:48:33 AM: success onPreInit — 2.285 s
7:48:33 AM: success delete html and css files from previous builds — 0.008 s
7:48:33 AM: success initialize cache — 0.009 s
7:48:33 AM: success copy gatsby files — 0.029 s
7:48:33 AM: success onPreBootstrap — 0.012 s
7:48:33 AM: success source and transform nodes — 0.123 s
7:48:34 AM: success building schema — 0.409 s
7:48:34 AM: success createPages — 0.137 s
7:48:34 AM: success createPagesStatefully — 0.061 s
7:48:34 AM: success onPreExtractQueries — 0.001 s
7:48:34 AM: success update schema — 0.226 s
7:48:34 AM: success extract queries from components — 0.121 s
7:48:35 AM: success run graphql queries — 0.269 s — 9/9 33.48 queries/second
7:48:35 AM: success write out page data — 0.006 s
7:48:35 AM: success write out redirect data — 0.001 s
7:48:35 AM: success onPostBootstrap — 0.001 s
7:48:35 AM: info bootstrap finished - 6.878 s
7:48:35 AM: Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
7:48:37 AM: Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
7:48:53 AM: Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
7:48:53 AM: Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
7:48:54 AM: Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
7:48:54 AM: Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
7:48:54 AM: Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
7:48:56 AM: success Building production JavaScript and CSS bundles — 21.212 s
7:48:59 AM: success Building static HTML for pages — 3.662 s — 8/8 22.12 pages/second
7:48:59 AM: info Done building in 31.761 sec
7:49:00 AM: Skipping functions preparation step: no functions directory set
7:49:00 AM: Caching artifacts
7:49:00 AM: Started saving node modules
7:49:00 AM: Finished saving node modules
7:49:00 AM: Started saving pip cache
7:49:00 AM: Finished saving pip cache
7:49:00 AM: Started saving emacs cask dependencies
7:49:00 AM: Finished saving emacs cask dependencies
7:49:00 AM: Started saving maven dependencies
7:49:00 AM: Finished saving maven dependencies
7:49:00 AM: Started saving boot dependencies
7:49:00 AM: Finished saving boot dependencies
7:49:00 AM: Started saving go dependencies
7:49:00 AM: Finished saving go dependencies
7:49:03 AM: Build script success
7:49:03 AM: Starting to deploy site from 'public/'
7:49:03 AM: Creating deploy tree 
7:49:03 AM: 14 new files to upload
7:49:03 AM: 0 new functions to upload
7:49:05 AM: Starting post processing
7:49:07 AM: Post processing done
7:49:07 AM: Site is live
7:49:29 AM: Finished processing build request in 2m35.959927412s
7:49:29 AM: Shutting down logging, 0 messages pending
```

**Pull request merged**
